[package]
name = "easy_password"
version = "0.1.0"
authors = ["Chris Williams <chrispwill@gmail.com>"]
description = "Easy password hashing (includes bcrypt)"
license = "MIT"
readme = "README.md"
keywords = ["bcrypt", "password", "hash"]

[dependencies]
hmac = "0.5"
sha2 = "0.7"
bcrypt = "0.2"
